name: Build-min_stage1

on:
  pull_request:
  push:
  schedule:
    - cron: '13 7,19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        MATRIX_CODE_NAME: ['bookworm', 'trixie', 'sid']

    env:
      CODE_NAME: ${{ matrix.MATRIX_CODE_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: bash min-stage1-$CODE_NAME.sh

      - name: Log in to the Docker container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # if: ${{ github.ref == 'refs/heads/main' }}

      - name: Publish the Docker image
        run: source tmp/bin/set-variables && docker push $DOCKER_IMAGE:latest
        # if: ${{ github.ref == 'refs/heads/main' }}

      - name: Delete old containers
        uses: actions/delete-package-versions@v5
        with: 
          package-name: "image-docker-debian-$CODE_NAME-min-stage1"
          package-type: 'docker'
          min-versions-to-keep: 3
          token: ${{ secrets.SPECIAL_TOKEN }}
        # if: ${{ github.ref == 'refs/heads/main' }}

      - name: Log out of the Docker container registry
        run: docker logout ghcr.io
        # if: ${{ github.ref == 'refs/heads/main' }}
